### ISSUE TITLE
delete command errors when copied_from image has already been deleted or replaced

### ISSUE THREAD

**Issue by wnkz** [wnkz/shipami#4]
```
DEBUG:shipami.cli:waiting for image ami-993403ff to be available
DEBUG:shipami.cli:deregistering ami-993403ff
DEBUG:shipami.cli:deleting snap-0159eb73cd31ff0ee
DEBUG:shipami.cli:deleting snap-002a7ba45cb2dc7f5
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/shipami-2.7/bin/shipami", line 11, in <module>
    load_entry_point('shipami', 'console_scripts', 'shipami')()
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/shipami-2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/shipami-2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/shipami-2.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/shipami-2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/shipami-2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/shipami-2.7/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/gmorpain/Documents/Development/github.com/wnkz/shipami/shipami/cli.py", line 147, in delete
    for deleted in shipami.delete(image_id, force):
  File "/Users/gmorpain/Documents/Development/github.com/wnkz/shipami/shipami/core.py", line 140, in delete
    self.__remove_copied_to(from_image, remove_copied_to)
  File "/Users/gmorpain/Documents/Development/github.com/wnkz/shipami/shipami/core.py", line 207, in __remove_copied_to
    copied_to = self.__get_tag(image, 'shipami:copied_to')
  File "/Users/gmorpain/Documents/Development/github.com/wnkz/shipami/shipami/core.py", line 248, in __get_tag
    tags = obj.get('Tags', []) if type(obj) is dict else obj.tags
  File "/usr/local/opt/pyenv/versions/2.7.13/envs/shipami-2.7/lib/python2.7/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by wnkz** [comment]
fixed by https://github.com/wnkz/shipami/commit/e855ed358695e97df40d19d5322356b7d741262f
